#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$ROOT/.voicepack-tmp"
OUT="$ROOT/public/audio/bai-choi"

rm -rf "$WORK"
mkdir -p "$WORK" "$OUT"
cd "$WORK"

echo "Installing audio utilities..."
sudo apt-get update -qq
sudo apt-get install -y -qq sox libsox-fmt-all ffmpeg >/dev/null

echo "Downloading Piper runtime + Vietnamese neural voice..."
curl -L --fail --retry 3 -o piper.tar.gz   https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_linux_x86_64.tar.gz
tar -xzf piper.tar.gz

MODEL_URL="https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/vi/vi_VN/vais1000/medium"
curl -L --fail --retry 3 -o vi_VN-vais1000-medium.onnx   "$MODEL_URL/vi_VN-vais1000-medium.onnx"
curl -L --fail --retry 3 -o vi_VN-vais1000-medium.onnx.json   "$MODEL_URL/vi_VN-vais1000-medium.onnx.json"

PIPER="$WORK/piper/piper"
MODEL="$WORK/vi_VN-vais1000-medium.onnx"

render_segment() {
  local text="$1"
  local out="$2"
  printf '%s\n' "$text" | "$PIPER"     --model "$MODEL"     --output_file "$out"
}

stylize_segment() {
  local input="$1"
  local output="$2"
  local cents="$3"
  local tempo="$4"

  sox "$input" "$output"     pitch "$cents"     tempo -s "$tempo"     reverb 16 35 55 45 0 0
}

silence() {
  local seconds="$1"
  local output="$2"
  sox -n -r 22050 -c 1 "$output" trim 0.0 "$seconds"
}

render_chant() {
  local slug="$1"
  local a="$2"
  local b="$3"
  local c="$4"
  local p1="$5"
  local p2="$6"
  local p3="$7"

  render_segment "$a" "$slug-1-raw.wav"
  render_segment "$b" "$slug-2-raw.wav"
  render_segment "$c" "$slug-3-raw.wav"

  stylize_segment "$slug-1-raw.wav" "$slug-1.wav" "$p1" 0.92
  stylize_segment "$slug-2-raw.wav" "$slug-2.wav" "$p2" 0.96
  stylize_segment "$slug-3-raw.wav" "$slug-3.wav" "$p3" 0.88

  silence 0.13 "$slug-pause1.wav"
  silence 0.10 "$slug-pause2.wav"

  sox     "$slug-1.wav" "$slug-pause1.wav"     "$slug-2.wav" "$slug-pause2.wav"     "$slug-3.wav"     "$slug-final.wav" gain -n -2

  ffmpeg -hide_banner -loglevel error -y     -i "$slug-final.wav"     -af "highpass=f=80,lowpass=f=9000,loudnorm=I=-16:TP=-1.5:LRA=7"     -codec:a libmp3lame -q:a 3     "$OUT/$slug-chant.mp3"
}

render_chant   "ong-am"   "Nghe đâu, một tiếng vang rền"   "bước chân rộn rã"   "cả miền hội xuân"   -120 70 150

render_chant   "ba-ga"   "Sáng ra, gà gáy ba hồi"   "giục người mở cửa"   "ra coi hội làng"   120 -40 130

render_chant   "cuu-chua"   "Chín hồi chuông vọng mái chùa"   "người nghe câu hát"   "đón mùa an vui"   -150 -20 110

cat > "$OUT/VOICE_PACK_LICENSE.txt" <<'EOF'
Bai Choi v0.4 baseline voice pack

Generated by the Minigame project from project-authored Vietnamese text.

Synthesis runtime:
- Piper TTS / rhasspy/piper release 2023.11.14-2.
- Piper source project license: MIT (see upstream repository).

Vietnamese voice:
- vi_VN-vais1000-medium from rhasspy/piper-voices.
- Model card: https://huggingface.co/rhasspy/piper-voices/blob/v1.0.0/vi/vi_VN/vais1000/medium/MODEL_CARD
- Model card identifies VAIS-1000 dataset and links its CC BY 4.0 license.
- This baseline is neural TTS, not a recording of a Bài Chòi artisan.

Files:
- ong-am-chant.mp3
- ba-ga-chant.mp3
- cuu-chua-chant.mp3
EOF

echo "Rendered:"
ls -lh "$OUT"
